name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  projectUrl: # change this
    required: true
    description: 'path to project'
  jobName:
    required: false
    description: 'Name of the job to filter on'
    default: 'release'
runs:
  using: 'node12'
  main: 'dist/index.js'
