name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  authToken: # change this
    required: true
    description: 'header token'
  projectUrl: # change this
    required: true
    description: 'path to project'
runs:
  using: 'node12'
  main: 'dist/index.js'
